# -*- coding: utf-8 -*-
"""questionA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X166XIKYF8DYVtmh5HNJftyT-11zBKTg
"""

import numpy as np
import pandas as pd

from numpy import array
from sklearn.preprocessing import Normalizer

data={'Duration (In Minutes)':[200, 300, 90, 120, 1000, 800, 85, 300, 400], 
        'Mood':['Dark', 'Semi-Dark', 'Bright', 'Semi-Dark', 'Bright', 'Bright', 'Bright', 'Bright', 'Dark'], 
        'Age Restriction':['Adult', 'Adult', 'Family', 'Adult', 'Family', 'Adult', 'Adult', 'Children', 'Adult'], 
        'Movie Rating':[9.8, 7.1, 8.5, 9.0, 6.3, 4.8, 7.6, 2.8, 9.0]}

dataset=pd.DataFrame(data, index=['Money Heist', 'Prison Break', 'Overcomer', 'Mosul', 'Selina', '24', 'Extraction', 'Boss Baby', 'Caliphate'])

dataset

print(dataset['Mood'].unique())

dataset['Mood'].value_counts()

one_hot_encoded_data = pd.get_dummies(dataset, columns=['Mood'])

print(one_hot_encoded_data)